/**
 * Generated Media Component
 * 
 * Displays images and audio generated by multimodal AI models (Gemini image/TTS).
 * Supports inline viewing, download, and playback functionality.
 * 
 * @see https://ai.google.dev/gemini-api/docs/image-generation
 * @see https://ai.google.dev/gemini-api/docs/speech-generation
 */
import React, { memo, useState, useCallback, useRef } from 'react';
import { Download, Play, Pause, Image as ImageIcon, Volume2, Maximize2, X, Copy, Check } from 'lucide-react';
import { cn } from '../../../utils/cn';

interface GeneratedImageProps {
  /** Base64-encoded image data */
  data: string;
  /** MIME type (e.g., 'image/png', 'image/jpeg') */
  mimeType: string;
  /** Index for multiple images */
  index?: number;
}

interface GeneratedAudioProps {
  /** Base64-encoded audio data (PCM or WAV) */
  data: string;
  /** MIME type (e.g., 'audio/wav', 'audio/pcm') */
  mimeType: string;
}

interface GeneratedMediaProps {
  /** Array of generated images */
  images?: Array<{ data: string; mimeType: string }>;
  /** Generated audio */
  audio?: { data: string; mimeType: string };
}

/**
 * Display a generated image with preview, expand, and download options
 */
const GeneratedImage: React.FC<GeneratedImageProps> = memo(({ data, mimeType, index = 0 }) => {
  const [isExpanded, setIsExpanded] = useState(false);
  const [copied, setCopied] = useState(false);
  
  const dataUrl = `data:${mimeType};base64,${data}`;
  
  const handleDownload = useCallback(() => {
    const link = document.createElement('a');
    link.href = dataUrl;
    const extension = mimeType.split('/')[1] || 'png';
    link.download = `generated-image-${index + 1}.${extension}`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }, [dataUrl, mimeType, index]);

  const handleCopyBase64 = useCallback(async () => {
    await navigator.clipboard.writeText(data);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [data]);

  return (
    <>
      <div className="group relative inline-block rounded-lg overflow-hidden border border-[var(--color-border-subtle)] bg-[var(--color-surface-1)]">
        {/* Image thumbnail */}
        <img
          src={dataUrl}
          alt={`Generated image ${index + 1}`}
          className={cn(
            "max-w-[300px] max-h-[200px] object-contain cursor-pointer transition-transform hover:scale-[1.02]",
            'rounded-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--color-accent-primary)]/40'
          )}
          onClick={() => setIsExpanded(true)}
          role="button"
          tabIndex={0}
          aria-label={`Expand generated image ${index + 1}`}
          onKeyDown={(e) => {
            if (e.key === 'Enter' || e.key === ' ') {
              e.preventDefault();
              setIsExpanded(true);
            }
          }}
        />
        
        {/* Overlay controls */}
        <div className="absolute inset-0 bg-black/0 group-hover:bg-black/20 group-focus-within:bg-black/20 transition-colors pointer-events-none" />
        <div className="absolute top-2 right-2 flex gap-1 opacity-0 group-hover:opacity-100 group-focus-within:opacity-100 transition-opacity">
          <button
            onClick={() => setIsExpanded(true)}
            className={cn(
              "p-1.5 bg-black/60 hover:bg-black/80 rounded text-white/80 hover:text-white transition-colors",
              'focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[var(--color-accent-primary)]/50'
            )}
            title="Expand"
          >
            <Maximize2 size={12} />
          </button>
          <button
            onClick={handleDownload}
            className={cn(
              "p-1.5 bg-black/60 hover:bg-black/80 rounded text-white/80 hover:text-white transition-colors",
              'focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[var(--color-accent-primary)]/50'
            )}
            title="Download"
          >
            <Download size={12} />
          </button>
          <button
            onClick={handleCopyBase64}
            className={cn(
              "p-1.5 bg-black/60 hover:bg-black/80 rounded text-white/80 hover:text-white transition-colors",
              'focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[var(--color-accent-primary)]/50'
            )}
            title="Copy base64"
          >
            {copied ? <Check size={12} className="text-[var(--color-success)]" /> : <Copy size={12} />}
          </button>
        </div>
        
        {/* Image info badge */}
        <div className="absolute bottom-2 left-2 text-[9px] bg-black/60 text-white/80 px-1.5 py-0.5 rounded">
          <ImageIcon size={9} className="inline mr-1" />
          {mimeType.split('/')[1]?.toUpperCase() || 'IMAGE'}
        </div>
      </div>

      {/* Expanded modal */}
      {isExpanded && (
        <div 
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm"
          onClick={() => setIsExpanded(false)}
        >
          <div className="relative max-w-[90vw] max-h-[90vh]" onClick={e => e.stopPropagation()}>
            <img
              src={dataUrl}
              alt={`Generated image ${index + 1}`}
              className="max-w-full max-h-[85vh] object-contain rounded-lg shadow-2xl"
            />
            <div className="absolute top-4 right-4 flex gap-2">
              <button
                onClick={handleDownload}
                className={cn(
                  "p-2 bg-black/60 hover:bg-black/80 rounded-lg text-white/80 hover:text-white transition-colors",
                  'focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[var(--color-accent-primary)]/50'
                )}
                title="Download"
              >
                <Download size={16} />
              </button>
              <button
                onClick={() => setIsExpanded(false)}
                className={cn(
                  "p-2 bg-black/60 hover:bg-black/80 rounded-lg text-white/80 hover:text-white transition-colors",
                  'focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[var(--color-accent-primary)]/50'
                )}
                title="Close"
              >
                <X size={16} />
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
});

GeneratedImage.displayName = 'GeneratedImage';

/**
 * Display generated audio with playback controls
 */
const GeneratedAudio: React.FC<GeneratedAudioProps> = memo(({ data, mimeType }) => {
  const [isPlaying, setIsPlaying] = useState(false);
  const [duration, setDuration] = useState<number | null>(null);
  const [currentTime, setCurrentTime] = useState(0);
  const audioRef = useRef<HTMLAudioElement>(null);
  
  const dataUrl = `data:${mimeType};base64,${data}`;
  
  const handlePlayPause = useCallback(() => {
    if (!audioRef.current) return;
    
    if (isPlaying) {
      audioRef.current.pause();
    } else {
      audioRef.current.play();
    }
    setIsPlaying(!isPlaying);
  }, [isPlaying]);

  const handleDownload = useCallback(() => {
    const link = document.createElement('a');
    link.href = dataUrl;
    const extension = mimeType.includes('wav') ? 'wav' : 'audio';
    link.download = `generated-audio.${extension}`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }, [dataUrl, mimeType]);

  const handleLoadedMetadata = useCallback(() => {
    if (audioRef.current) {
      setDuration(audioRef.current.duration);
    }
  }, []);

  const handleTimeUpdate = useCallback(() => {
    if (audioRef.current) {
      setCurrentTime(audioRef.current.currentTime);
    }
  }, []);

  const handleEnded = useCallback(() => {
    setIsPlaying(false);
    setCurrentTime(0);
  }, []);

  const formatTime = (seconds: number) => {
    const mins = Math.floor(seconds / 60);
    const secs = Math.floor(seconds % 60);
    return `${mins}:${secs.toString().padStart(2, '0')}`;
  };

  const progress = duration ? (currentTime / duration) * 100 : 0;

  return (
    <div className="flex items-center gap-3 p-3 rounded-lg border border-[var(--color-border-subtle)] bg-[var(--color-surface-1)]">
      <audio
        ref={audioRef}
        src={dataUrl}
        onLoadedMetadata={handleLoadedMetadata}
        onTimeUpdate={handleTimeUpdate}
        onEnded={handleEnded}
      />
      
      {/* Play/Pause button */}
      <button
        onClick={handlePlayPause}
        className={cn(
          'p-2 rounded-full transition-colors',
          isPlaying 
            ? 'bg-[var(--color-accent-primary)] text-[var(--color-text-on-accent)]' 
            : 'bg-[var(--color-surface-2)] text-[var(--color-text-primary)] hover:bg-[var(--color-surface-3)]'
        )}
      >
        {isPlaying ? <Pause size={14} /> : <Play size={14} className="ml-0.5" />}
      </button>
      
      {/* Waveform / Progress */}
      <div className="flex-1 flex flex-col gap-1">
        <div className="flex items-center gap-2">
          <Volume2 size={12} className="text-[var(--color-text-muted)]" />
          <span className="text-[10px] text-[var(--color-text-secondary)]">Generated Audio</span>
        </div>
        <div className="relative h-1 bg-[var(--color-surface-2)] rounded-full overflow-hidden">
          <div 
            className="absolute h-full bg-[var(--color-accent-primary)] transition-all duration-100"
            style={{ width: `${progress}%` }}
          />
        </div>
        <div className="flex justify-between text-[9px] text-[var(--color-text-muted)]">
          <span>{formatTime(currentTime)}</span>
          <span>{duration ? formatTime(duration) : '--:--'}</span>
        </div>
      </div>
      
      {/* Download button */}
      <button
        onClick={handleDownload}
        className="p-1.5 text-[var(--color-text-muted)] hover:text-[var(--color-text-primary)] transition-colors"
        title="Download"
      >
        <Download size={14} />
      </button>
    </div>
  );
});

GeneratedAudio.displayName = 'GeneratedAudio';

/**
 * Main component to display all generated media for a message
 */
export const GeneratedMedia: React.FC<GeneratedMediaProps> = memo(({ images, audio }) => {
  const hasMedia = (images && images.length > 0) || audio;
  
  if (!hasMedia) return null;

  return (
    <div className="mt-3 space-y-3">
      {/* Images */}
      {images && images.length > 0 && (
        <div className="flex flex-wrap gap-2">
          {images.map((image, index) => (
            <GeneratedImage
              key={`image-${index}`}
              data={image.data}
              mimeType={image.mimeType}
              index={index}
            />
          ))}
        </div>
      )}
      
      {/* Audio */}
      {audio && (
        <GeneratedAudio data={audio.data} mimeType={audio.mimeType} />
      )}
    </div>
  );
});

GeneratedMedia.displayName = 'GeneratedMedia';
